// app/src/routes/settings/+page.svelte
<script lang="ts">
  import { userData } from "../userData";
  import { toast } from "../toast";

  let temp = $state({ mediaPath: $userData.mediaPath, port: $userData.port });

  $effect(() => {
    temp.mediaPath = $userData.mediaPath;
    temp.port = $userData.port;
  });

  let children = $state<string[]>([]);

  let showPicker = $state(false);

  function getDirInfo(path: string) {
    fetch(`http://localhost:8000/api/get_dir_info?path=${path}`)
      .then((res) => res.json())
      .then((data) => {
        temp.mediaPath = path;
        children = data;
        showPicker = true;
      });
  }

  function saveChange() {
    fetch("http://localhost:8000/api/change_user_data", {
      method: "PATCH",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ path: temp.mediaPath, port: temp.port }),
    }).then((res) => {
      if (!res.ok) {
        $toast.error("Couldn't save user data.")
      } else {
        $userData.mediaPath = temp.mediaPath;
        $userData.port = temp.port;
        $toast.success("User data saved.")
      }
    });
  }
  function prevDir() {
    let parts = temp.mediaPath.split("/");
    parts.pop();
    let path = parts.join("/");
    getDirInfo(path === "" ? "/" : path);
  }
</script>

<div class="w-[60%] h-screen m-auto flex flex-col gap-5 mt-28 relative">
  <span class="text-white text-lg font-semibold">Port</span>
  <input
    type="number"
    class="w-[60%] h-8 bg-white rounded-xl outline-none p-3"
    value={temp.port}
    onchange={(e) => (temp.port = parseInt(e.currentTarget?.value))}
  />
  <span class="text-white text-lg font-semibold">Media Directory</span>
  <div class="w-full flex items-center gap-5">
    <input
      type="text"
      class="w-[60%] h-8 bg-white rounded-xl outline-none p-3"
      value={temp.mediaPath}
      readonly
    />
    <button
      class="gradient-bg px-3 py-2 text-white font-semibold rounded-xl cursor-pointer"
      onclick={() => getDirInfo(temp.mediaPath)}>Choose</button
    >
  </div>
  {#if showPicker}
    <div
      class="absolute top-0 left-1/2 -translate-x-1/2 w-[60%] h-[60%] bg-white flex flex-col p-5 gap-2 rounded-xl"
    >
      <div class="flex gap-2 items-center">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="cursor-pointer"
          onclick={() => prevDir()}><path d="m15 18-6-6 6-6" /></svg
        >
        <h4 class="text-lg font-bold">{temp.mediaPath}</h4>
      </div>
      <hr />
      <div class="flex flex-col overflow-y-scroll w-full h-[80%]">
        {#each children as item}
          <button
            class="flex cursor-pointer hover:bg-[#1d2f43] hover:text-white font-semibold p-2 rounded-lg gap-2"
            onclick={() =>
              getDirInfo(
                temp.mediaPath === "/"
                  ? temp.mediaPath + item
                  : temp.mediaPath + "/" + item,
              )}
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="lucide lucide-folder-icon lucide-folder"
              ><path
                d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"
              /></svg
            >
            <li class="list-none">{item}</li>
          </button>
        {/each}
      </div>
      <button
        class="font-semibold gradient-bg text-white px-3 p-2 text-lg rounded-lg cursor-pointer absolute bottom-5 right-5"
        onclick={() => (showPicker = false)}>Close</button
      >
    </div>
  {/if}
  <button
    class="font-semibold gradient-bg text-white px-3 p-2 text-lg rounded-lg cursor-pointer self-start"
    disabled={temp.mediaPath === $userData.mediaPath &&
      temp.port === $userData.port}
    onclick={saveChange}>Save</button
  >
</div>

// app/src/components/Settings.tsx
import React, { useEffect, useState } from "react";
import {
  X,
  ChevronRight,
  ChevronDown,
  FolderClosed,
  FileText,
  Image,
  Film,
  File
} from "lucide-react";
import { toast } from "react-toastify";

type UserData = {
  mediaPath: string
}

export default function Settings() {
  const [showFolderPicker, setShowFolderPicker] = useState<boolean>(false);
  const [userData, setUserData] = useState<UserData>()
  const [tempFolderPath, setTempFolderPath] = useState<string>(userData?.mediaPath || "")

  useEffect(() => {
    fetch(`${import.meta.env.VITE_API_URL}/get-user-data`, {
      method: "GET",
      headers: {
        "Content-Type": "application/json"
      }
    }).then(res => {
      return res.json()
    }).then(data => {
      if (data.status === "success") {
        setUserData(data.data)
      }
      else toast.error(data.message)
    })
  }, [])

  useEffect(() => {
    setTempFolderPath(userData?.mediaPath || "")
  }, [userData])

  return (
    <div className="flex flex-col justify-self-center w-4/5 p-10">
      <label htmlFor="path" className="text-lg text-white self-start">
        Your movies directory:
      </label>
      <div className="flex gap-2">
        <input
          type="text"
          id="path"
          className="border-white border-2 outline-none py-1 px-3 w-2/4 text-white text-lg"
          value={tempFolderPath === userData?.mediaPath ? userData.mediaPath : tempFolderPath}
          readOnly
        />
        {tempFolderPath === userData?.mediaPath && <button
          className="bg-purple-950 text-white p-3 rounded-xl font-bold text-md cursor-pointer"
          onClick={() => setShowFolderPicker(true)}
        >
          Choose
        </button>}
        {tempFolderPath !== userData?.mediaPath && <button
          className="bg-purple-950 text-white p-3 rounded-xl font-bold text-md cursor-pointer"
          onClick={() => setTempFolderPath(userData?.mediaPath as string)}
        >
          Cancel
        </button>}
        {tempFolderPath !== userData?.mediaPath && <button
          className="bg-green-500 text-white p-3 rounded-xl font-bold text-md cursor-pointer"
          onClick={() => {
            setShowFolderPicker(false)
            fetch(`${import.meta.env.VITE_API_URL}/save/media-path`, {
              method: "POST",
              headers: {
                "Content-Type": "application/json"
              },
              body: JSON.stringify({
                "path": tempFolderPath
              })
            }).then(res => {
              return res.json()
            }).then(data => {
              if (data.status === "success") {
                setUserData({...userData, mediaPath: tempFolderPath})
                toast.success(data.message)
              } else {
                toast.error(data.message)
              }
            }).catch(err => {
              toast.error((err as Error).message)
            })
          }}
        >
          Save
        </button>}
      </div>
      {showFolderPicker && (
        <FileSystem
          setShowFolderPicker={setShowFolderPicker}
          setFolderPath={setTempFolderPath}
        />
      )}
    </div>
  );
}

function FileSystem({
  setShowFolderPicker,
  setFolderPath,
}: {
  setShowFolderPicker: React.Dispatch<React.SetStateAction<boolean>>;
  setFolderPath: React.Dispatch<React.SetStateAction<string>>;
}) {
  
  const [selectedFolder, setSelectedFolder] = useState<string>("")
  const [rootDirs, setRootDir] = useState<DirectoryData[]>()

  useEffect(() => {
    fetch(`${import.meta.env.VITE_API_URL}/getDirInfo?dir=${"/"}`, {
      method: "GET",
      headers: {
        "Content-Type": "application/json"
      }
    }).then(res => {
      return res.json()
    }).then((data : DirectoryData[]) => {
      setRootDir(data)
    })
  }, [])

  return (
    <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 min-w-[20vw] bg-white flex flex-col p-5">
      <X
        className="absolute top-0 right-0 cursor-pointer"
        onClick={() => setShowFolderPicker(false)}
      />
      <h2 className="text-lg font-bold p-2">Choose a folder:</h2>
      <div className="max-h-[40vh] overflow-y-scroll">
      {rootDirs && rootDirs?.length > 0 && rootDirs.map(dir => {
        return <Directory data={dir} indent={1} path={`/${dir.name}`} selectedFolder={selectedFolder} setSelectedFolder={setSelectedFolder} />
      })}
      </div>
      <button className="self-end mr-5 py-1 p-3 bg-blue-400 rounded-xl text-white" onClick={() => setFolderPath(selectedFolder)} disabled={selectedFolder === ""}>Choose</button>
    </div>
  );
}

type DirectoryData = {
  name: string;
  type: string;
};

const Icons: { [key: string]: any } = {
  dir: <FolderClosed />,
  txt: <FileText />,
  image: <Image />,
  video: <Film />,
  file: <File />
};

function Directory({
  data,
  indent,
  path,
  selectedFolder,
  setSelectedFolder,
}: {
  data: DirectoryData;
  indent: number;
  path?: string;
  selectedFolder: string;
  setSelectedFolder: React.Dispatch<React.SetStateAction<string>>;
}) {
  const [open, setOpen] = useState<boolean>(false);
  const [children, setChildren] = useState<DirectoryData[]>()
  path = path ? path : data.name;

  function handleOnclick() {
    if (!open) setOpen(true);
    else return
    if (data.type === "dir") setSelectedFolder(path as string);
    fetch(`${import.meta.env.VITE_API_URL}/getDirInfo?dir=${path}`, {
      method: "GET",
      headers: {
        "Content-Type": "application/json"
      }
    }).then(res => {
      return res.json()
    }).then((data : DirectoryData[]) => {
      setChildren(data)
    })
  }


  return (
    <>
      <div
        className={`flex items-center gap-2 cursor-pointer ${
          selectedFolder === path ? "bg-blue-300" : ""
        } hover:bg-blue-300`}
        style={{ paddingLeft: `${indent * (data.type !== "dir" ? 16 : 8)}px` }}
        onClick={handleOnclick}
      >
        {data.type === "dir" &&
          (!open ? (
            <ChevronRight className="cursor-pointer" />
          ) : (
            <ChevronDown
              className="cursor-pointer"
              onClick={() => {
                setOpen(false);
                setSelectedFolder("");
              }}
            />
          ))}
        {Icons[data.type]}
        <p className="text-lg">{data.name}</p>
      </div>
      {open && children && children?.length > 0 && children.map(dir => {
        return <Directory data={dir} indent={indent + 1} path={`${path}/${dir.name}`} selectedFolder={selectedFolder} setSelectedFolder={setSelectedFolder} />
      })}
    </>
  );
}
